site_name: Divisão de Nacionalização

nav:
  - Estrutura: index.md
  - SILOMS:
      - Requisições de ressuprimento: siloms/requisicaoRessuprimento.md
      - Listagem de PTNs: siloms/listaPTN.md  
  - Sobre: sobre.md

theme: 
  name: material
  language: pt
  palette:
    scheme: slate