site_name: Divisão de Nacionalização e Qualificação

nav:
  - Estrutura: index.md
  - Legislação: 
    - MCA & ICA & RICA: legislacao/legislacao.md
    - NPAs: legislacao/npa/index.md
    - Processos: legislacao/plog/index.md
  - SILOMS:
    - Requisições:
      - Ressuprimento: siloms/requisicao/requisicoes ressuprimento.md    
      - Emergência: siloms/requisicao/requisicoes emergencia.md
    - Valor de referência: 
        - Histórico: siloms/referencia/valor historico.md
        - Situacional: siloms/referencia/valor situacional.md
    - Recebimento de material: siloms/recebimento material.md        
  - Sobre: sobre.md
  

theme: 
  name: material
  language: pt  

markdown_extensions:
  - admonition
  - def_list