site_name: Divisão de Nacionalização

nav:
  - Estrutura: index.md
  - SILOMS:
      - Listar requisições de ressuprimento: siloms/listar requisicao ressuprimento.md
      - Receber material: siloms/receber material.md      
  - Sobre: sobre.md

theme: 
  name: material
  language: pt
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - def_list