site_name: Divisão de Nacionalização

nav:
  - Estrutura: index.md
  - Procedimentos: 
      - Requisições de ressuprimento: proc/requisicaoRessuprimento.md
      - Listagem de PTNs: proc/listaPTN.md  
  - Sobre: sobre.md

theme: 
  name: material
  language: pt
  palette:
    scheme: slate