site_name: Divisão de Nacionalização

nav:
  - Estrutura: index.md
  - SILOMS:
      - Requisições de ressuprimento: siloms/requisicoes ressuprimento.md
      - Requisições em emergência: siloms/requisicoes emergencia.md
      - Recebimento de material: siloms/recebimento material.md      
  - Sobre: sobre.md

theme: 
  name: material
  language: pt
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - def_list